M48
; DRILL file KiCad 10.0.5 date 2026-08-24T12:30:49
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-24T12:30:49-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.540
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C4.000
%
G90
G05
T1
X90.302Y-47.763
X110.622Y-47.763
T2
X65.782Y-40.383
X65.782Y-72.383
X115.782Y-40.383
X115.782Y-72.383
T3
X95.382Y-40.143
X105.542Y-40.143
M30
